name: Test Python Package from Nexus

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependency from Nexus
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          NEXUS_URL: ${{ secrets.NEXUS_URL }}
        run: |
          pip install ml-lib-ejemplo \
            --index-url http://${NEXUS_USERNAME}:${NEXUS_PASSWORD}@${NEXUS_URL} \
            --trusted-host ec2-3-84-125-90.compute-1.amazonaws.com
